<?php

return [
    'enabled' => env('PROBE_GUARD_ENABLED', true),

    'table_names' => [
        'blocked_ips'         => 'probe_guard_blocked_ips',
        'suspicious_requests' => 'probe_guard_suspicious_requests',
    ],

    'middleware_alias' => 'probe-guard',

    'auto_register_global_middleware' => env('PROBE_GUARD_GLOBAL_MIDDLEWARE', false),

    'block_duration' => env('PROBE_GUARD_BLOCK_DURATION', '7 days'),

    'extend_existing_blocks' => true,

    'blocked_response' => [
        'status' => 403,
        'body'   => 'Access blocked temporarily due to suspicious activity.',
    ],

    'detected_response' => [
        'status' => 404,
        'body'   => null,
    ],

    'ip_whitelist' => array_values(array_filter(array_map(
        'trim',
        explode(',', env('PROBE_GUARD_IP_WHITELIST', '127.0.0.1,::1'))
    ))),

    'trusted_proxy_headers' => [
        'cf-connecting-ip',
    ],

    'trusted_proxies' => [],

    'safe_paths' => [
        '',
        'favicon.ico',
        'robots.txt',
        'sitemap.xml',
    ],

    'safe_prefixes' => [],

    'exact_paths' => [
        '.env',
        '.env.backup',
        '.env.example',
        '.git/config',
        '_secrets',
        'access.log',
        'access_log',
        'amplify/team-provider-info.json',
        'ansible.cfg',
        'adminer.php',
        'api/rest/v1',
        'api/rest/v2',
        'appsettings.json',
        'asset-manifest.json',
        'azure-pipelines.yml',
        'backend.tf',
        'bitbucket-pipelines.yml',
        'browserconfig.xml',
        'buildkite.yml',
        'certificate',
        'certificate.crt',
        'certificate.pem',
        'cert',
        'changelog',
        'changelog.md',
        'chart.yaml',
        'clientaccesspolicy.xml',
        'composer.json',
        'composer.lock',
        'config.php',
        'config.json',
        'crossdomain.xml',
        'database.sql',
        'database.sqlite',
        'docker-compose.dev.yml',
        'docker-compose.override.yml',
        'docker-compose.prod.yml',
        'docker-compose.staging.yml',
        'docker-compose.yaml',
        'docker-compose.yml',
        'dockerfile',
        'dockerfile.dev',
        'dockerfile.prod',
        'dockerfile.staging',
        'error.log',
        'error_log',
        'inventory.ini',
        'inventory.yml',
        'jenkins.groovy',
        'jenkinsfile',
        'kustomization.yaml',
        'middleware.js',
        'middleware.ts',
        'next.config.js',
        'next.config.mjs',
        'next.config.ts',
        'outputs.tf',
        'package.json',
        'package-lock.json',
        'playbook.yml',
        'phpinfo.php',
        'precache-manifest',
        'private-key',
        'private.key',
        'private.pem',
        'private_key',
        'private_keys',
        'providers.tf',
        'readme',
        'readme.md',
        'sam-template.yaml',
        'server.js',
        'serverless.json',
        'serverless.yaml',
        'serverless.yml',
        'shell.php',
        'terraform/main.tf',
        'values.yaml',
        'variables.tf',
        'vault.yml',
        'web.config',
        'wp-login.php',
        'xmlrpc.php',
    ],

    'path_prefixes' => [
        '.git',
        '.svn',
        '_cat',
        '_cluster',
        '_debug',
        '_dev',
        '_next',
        '_profiler',
        '_vercel',
        'actuator',
        'administrator',
        'api/api-keys',
        'api/certificates',
        'api/certs',
        'api/credentials',
        'api/keys',
        'api/private-keys',
        'api/public-keys',
        'api/secrets',
        'api/tokens',
        'app/config',
        'app/etc',
        'backups',
        'cgi-bin',
        'credentials',
        'docker',
        'dumps',
        'elasticsearch',
        'grafana',
        'kibana',
        'package-updates',
        'php-cgi',
        'phpmyadmin',
        'plugins',
        'pma',
        'proc',
        'storage/logs',
        'var/log',
        'vendor/phpunit',
        'wp-admin',
        'wp-content',
        'wp-includes',
        'wp-json',
        'wordpress',
        'xampp',
    ],

    'extensions' => [
        'bak',
        'conf',
        'env',
        'ini',
        'key',
        'old',
        'pem',
        'sql',
    ],

    'regex_patterns' => [
        '#(^|/)\.\./#',
        '#(^|/)(__admin|__debug|__dev|__fixtures__|__internal|__mocks__|__snapshots__|__test|__tests__)(/|$)#',
        '#(^|/)(_admin|_debug|_dev|_internal|_private|_protected|_secret|_snapshot|_mapping|_template|_aliases|_nodes|_search)(/|$)#',
        '#(^|/)(setup|install|installer|upgrade|web-installer)(/|$)#',
        '#(^|/)etc/(passwd|shadow|hosts|crontab|environment|profile|sudoers|redis\.conf|php/php\.ini|apache2/apache2\.conf|nginx/nginx\.conf|ssh/sshd_config|mail/sendmail\.cf|postfix/main\.cf|exim4/)#',
        '#(^|/)proc/(self|1|cpuinfo|meminfo|mounts|net|version)(/|$)#',
        '#(^|/)var/log/(nginx|apache2)/#',
        '#(^|/)(runtime/(cache|logs)|logs?/[^/]+\.(log|txt)|access_log|error_log|access\.log|error\.log)$#',
        '#(^|/)(backup|dump|database|db|storage|public|dist|build|release|app|code|sources|source|www|site)\.(7z|bz2|gz|sql|tar|tar\.gz|tgz|zip)$#',
        '#(^|/)(backup|backups|dump|dumps)(/|$)#',
        '#(^|/)(phpinfo|info|redis/info|api/redis/info|solr/admin|webmin|sysinfo\.cgi|software/.*\.cgi|servers/.*\.cgi|proc/index\.cgi|dnscfg\.cgi)(/|$)#',
        '#(^|/)(app_dev\.php|index_dev\.php|_profiler)(/|$)#',
        '#(^|/)(xampp|php-cgi|cgi-bin)/(php|php5|php-cgi)(\.exe)?#',
        '#(^|/)rest/(oauth[12]-credential/auth|credentials-for-node|credential-translation|workflows|variables|users|tags|settings|node-types|logout|login|license|executions)(/|$)#',
        '#(^|/)api/v1/(workflows|executions)(/|$)#',
        '#(^|/)wp-(admin|content|includes|config)|(^|/)wp-json(/|$)#',
        '#(^|/)(dockerfile|docker-compose|ansible\.cfg|playbook\.yml|inventory\.(ini|yml)|vault\.yml|.*\.tf|serverless\.(json|ya?ml)|jenkinsfile|jenkins\.groovy|.*-pipelines\.yml|buildkite\.yml|chart\.yaml|values\.yaml|kustomization\.yaml)$#i',
        '#(^|/)(private[-_]?keys?|credentials|secrets|keys)(/|\.|$)#',
        '#(^|/)etc/passwd$#',
        '#(^|/)(cmd|shell|wso|c99|r57)\.php$#',
    ],

    'query_keys' => [
        'dns' => 'Suspicious DNS probe',
    ],

    'query_value_contains' => [
        'name' => [
            'dnsmeasure' => 'Suspicious DNS probe',
        ],
        'file' => [
            '../'  => 'Suspicious file traversal probe',
            '..\\' => 'Suspicious file traversal probe',
            '.env' => 'Suspicious environment file probe',
        ],
        'action' => [
            'phpinfo' => 'Suspicious phpinfo probe',
        ],
        'do' => [
            'phpinfo' => 'Suspicious phpinfo probe',
        ],
        'mode' => [
            'phpinfo' => 'Suspicious phpinfo probe',
        ],
        'page' => [
            'phpinfo' => 'Suspicious phpinfo probe',
        ],
        'phpinfo' => [
            '1' => 'Suspicious phpinfo probe',
        ],
        'view' => [
            'phpinfo' => 'Suspicious phpinfo probe',
        ],
    ],

    'logging' => [
        'enabled' => true,
        'channel' => null,
    ],

    'filament' => [
        'enabled'          => true,
        'navigation_group' => 'Security',
    ],
];
